#49 solved by adding name input validation and a SnackBar notification.
eludris-community/eludris_flutter pull request #56
Opened 2023-01-12 17:12 UTC by SichangiFelix

Here are some screenshots of the functionality.

This screenshot shows behavior with less than two characters

![name less than 2](https://user-images.githubusercontent.com/62835310/212133439-342dc97e-bc89-4973-88dc-16637eaf0576.png)

This screenshot shows behavior with name having more than 2 and less than 32  characters

![correct number of characters](https://user-images.githubusercontent.com/62835310/212133885-53ceed41-7c98-4231-9433-ef443db9a586.png)

This screenshot shows behavior with more than 32characters

![name more than 32](https://user-images.githubusercontent.com/62835310/212134007-95badf6d-a7bf-4296-9998-1958d9585c4f.png)

2023-01-12 17:15 UTC, EnokiUN approved these changes

2023-01-12 19:20 UTC, teaishealthy requested changes
Currently if the user keeps typing after 32 characters multiple Snackbars will be shown.
I would replace the Snackbar with hint text under the input would as that is less annoying.

I'd love to hear other suggestions and ideas if you got any!

2023-01-12 19:20 UTC, teaishealthy commented on lib/routes/home.dart
> +  Home({Key? key}) : super(key: key);
```suggestion
  const Home({Key? key}) : super(key: key);
```

2023-01-12 19:20 UTC, teaishealthy commented on lib/routes/home.dart
> +              'Ensure the name is more than 2 and less than 32 characters long')));
```suggestion
              'Username must be between 2 and 32 characters long')));
```

2023-01-12 19:35 UTC, SichangiFelix commented on lib/routes/home.dart
> +  Home({Key? key}) : super(key: key);
Yeah that sounds better, let me do that

2023-01-13 07:34 UTC, SichangiFelix reviewed
I have made the requested changes

2023-01-24 17:21 UTC, teaishealthy requested changes
- State updates even where there is no new state
- The Widget being hidden causes the button to shift, try using Opacity?

2023-02-03 20:33 UTC, teaishealthy commented
@SichangiFelix Any updates?

2023-02-05 20:04 UTC, SichangiFelix commented
> 

I can have a look at the raised issue...

2023-02-14 20:17 UTC, teaishealthy commented
Closing due to no updates

2023-02-14 20:17 UTC, closed without merging